### ISSUE TITLE
Initial Architecture

### ISSUE THREAD

**Issue by austencollins** [serverless/serverless-client-s3#1]
- [ ] Looks for a `client` folder in the project root and a `s-client-s3.json` file in that folder or one level of subfolders.
- [ ] The `s-client-s3.json` file contains configuration for the website.  For example, the website bucket.  
- [ ] You should be able to specify file or folder paths of all assets you'd like to be uploaded.
- [ ] Creates or updates the website S3 bucket before upload
- [ ] Should overwrite any assets in S3 by default on upload.  There should also be an option to only upload assets that do not exist.
- [ ] Use the following key structure:  `clientName/js/`, `clientName/css/`, etc.
- [ ] Specify a build script to run.  If set, this should run before upload. 

Sample `s-client-s3.json` file:

```
{
   "name" : ""    // Name of client.  E.g., "dashboard", "admin"
   "cloudfrontDistributionId": null,
   "build" : "path/build.js" // Optional path and file to a build script
}
```

**Comment by pmuens** [comment]
Should all those assets be uploaded in the Serverless S3 bucket? Because `static website hosting` needs to be enabled to serve those assets (and this may leak other files to the outside).

Here's a sample CloudFormation template one could use for static website hosting:
https://s3.amazonaws.com/autodevbot.com/CloudFormation/S3-Static-Website.json

**Comment by austencollins** [comment]
Nice @pmuens!  Good point.  Let's pass on the "Use existing project bucket" option for now.  Thanks for the resource :)

**Comment by eggyal** [comment]
One should be able to add additional CloudFormation configuration in this `client` folder too, e.g. to provision CloudFront.

**Comment by austencollins** [comment]
@eggyal Another good point.  We'll make sure the framework checks in ALL folders for `s-resources-cf.json` files.

**Comment by eahefnawy** [comment]
Supporting @pmuens point, I think this plugin should focus on deploying a web client, not general assets. I think these are two different things. Setting a bucket to host a website should only serve that purpose, otherwise the assets will be leaked.

With that in mind, I'm not sure understand the need of an `s-client-s3.json` file or any of the properties you mentioned. I've pushed some initial code and here's how it works (WIP):
- You create a `clients` folder in the root of your project.
- This folder could contain subfolders for different web clients.
- The plugin reads this `clients` folder and creates a website bucket for each client, and uploads all the contents of each client to the corresponding bucket.

It imitates how function deploy works, so users would feel right at home with `sls client deploy`.

To start out, I'm using a nodejs module called `s3-site`, which is pretty neat. However I think it's best if we leave that dependency and borrow the code into our own repo because this module was last updated in 2014. The `s3-website` node module you suggested @ac360 was too simple for our purposes, it just uploads a single `index.html` file, while we need to upload entire client directories along with css/js/imgs...etc

**Comment by remicastaing** [comment]
Absolutely awesome! Wouldn't it be great to be able to "build" the static content before uploading it.

```
{
   "name" : ""    // Name of client.  E.g., "dashboard", "admin"
   "build" : "path/build.js" // Optional path and file to a build script
   "distPaths": {
      "img":  [], // Can contain files or folders.  Maybe RegEx patterns should be used here, like our lambda "excludePatterns".
      "js":   [],
      "css":  [],
      "html": [],
      "other":[]
   }
}
```

The build script would drop the build content in the dist path.

Another option could be to run a build command like `grunt build` or `gulp build`.

**Comment by pmuens** [comment]
:+1: for the build process!

**Comment by austencollins** [comment]
Updated to include the build script.  Nice work guys

**Comment by eahefnawy** [comment]
First version of the plugin was published :) ... it works a little differently than described here, but I think it yields much better user experience. Let me know what you guys think of this first version, and i can adjust it for your needs based on your feedback :)

**Comment by pmuens** [comment]
:+1: Great work! Used it today and got a site up and running in less than a minute. Good job!

**Comment by eahefnawy** [comment]
@pmuens awesome! Could you please let us know your workflow when developing front end websites? are you using the `src` & `dist` folders flow with a build script in between?

**Comment by austencollins** [comment]
:+1: Nice @pmuens and great job @eahefnawy!!!!

**Comment by kevinold** [comment]
Great job @eahefnawy and @pmuens!  I'll use this for a React / ES6 based client site soon and will be packaging with webpack and share my usage.  I'll likely have something the 1st or 2nd week in March as next week I'm traveling.

I'll certainly report back!

**Comment by pmuens** [comment]
@eahefnawy Yes, I think that the `src` and `dist` folder structure makes sense.

I started a plugin for static asset serving myself a few weeks ago but I totally missed this kind of folder structure. After a few uploads I realized that this is needed because for very large apps you need this kind of build system support.
