### ISSUE TITLE
Rename bucket

### ISSUE THREAD

**Issue by pmuens** [serverless/serverless-client-s3#3]
It would be great if the bucket name is similar to the serverless bucket name where all the serverless files are stored (this way one can directly identify that both buckets belong to one project).

**Comment by eahefnawy** [comment]
agreed! that's why we're adding the project name to the client bucket. The name spacing for both project and client buckets is a little different, mainly because of the difference of handling regions in both situations, but I think we can make that work somehow.

There's some discussion on giving the user total control over the bucket name. [Check this issue for more info](https://github.com/serverless/serverless/issues/602)

**Comment by pmuens** [comment]
Great! :+1:
